name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'
      - '.github/**'
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: write
      actions: read
      security-events: write
    uses: gattolab/infra-deployments/.github/workflows/reusable-workflow-ci.yml@d21206910ece64851781bf98c39b1fce7931959a
    with:
      app_name: wrappp
      deployment_path: manifest/wrappp/
      build_args: --build-arg GO_VERSION=${{ vars.GO_VERSION }}
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
